# enes193/__init__.py

from .Enes193 import Enes193
from enes193.tank import tank
from . import mission as _m

# Export constants normally (optional, still useful)
DEPTH = _m.DEPTH
WATER_TYPE = _m.WATER_TYPE
DIRECTION = _m.DIRECTION
LENGTH = _m.LENGTH
HEIGHT = _m.HEIGHT

CYCLE = _m.CYCLE
MAGNETISM = _m.MAGNETISM

WEIGHT = _m.WEIGHT
MATERIAL_TYPE = _m.MATERIAL_TYPE

NUM_CANDLES = _m.NUM_CANDLES
TOPOGRAPHY = _m.TOPOGRAPHY

LOCATION = _m.LOCATION

LED_COLOR = _m.LED_COLOR
VOLTAGE_OUTPUT = _m.VOLTAGE_OUTPUT

PLUS_X = _m.PLUS_X
MINUS_X = _m.MINUS_X
PLUS_Y = _m.PLUS_Y
MINUS_Y = _m.MINUS_Y

MAGNETIC = _m.MAGNETIC
NOT_MAGNETIC = _m.NOT_MAGNETIC

HEAVY = _m.HEAVY
MEDIUM = _m.MEDIUM
LIGHT = _m.LIGHT

FOAM = _m.FOAM
PLASTIC = _m.PLASTIC

TOP_A = _m.TOP_A
TOP_B = _m.TOP_B
TOP_C = _m.TOP_C

FRESH_UNPOLLUTED = _m.FRESH_UNPOLLUTED
FRESH_POLLUTED = _m.FRESH_POLLUTED
SALTY_UNPOLLUTED = _m.SALTY_UNPOLLUTED
SALTY_POLLUTED = _m.SALTY_POLLUTED

BOTH = _m.BOTH
NEITHER = _m.NEITHER
ADJACENT = _m.ADJACENT
DIAGONAL = _m.DIAGONAL

VOLTAGE_1 = _m.VOLTAGE_1
VOLTAGE_2 = _m.VOLTAGE_2
VOLTAGE_3 = _m.VOLTAGE_3
VOLTAGE_4 = _m.VOLTAGE_4
VOLTAGE_5 = _m.VOLTAGE_5

WHITE = _m.WHITE
RED = _m.RED
YELLOW = _m.YELLOW
GREEN = _m.GREEN
BLUE = _m.BLUE


# ---- THE IMPORTANT PART ----
# Inject constants into __main__ so students can type DEPTH without importing it.
try:
    import __main__ as _main

    _EXPORTS = {
        # types
        "DIRECTION": DIRECTION, "LENGTH": LENGTH, "HEIGHT": HEIGHT,
        "CYCLE": CYCLE, "MAGNETISM": MAGNETISM,
        "WEIGHT": WEIGHT, "MATERIAL_TYPE": MATERIAL_TYPE,
        "NUM_CANDLES": NUM_CANDLES, "TOPOGRAPHY": TOPOGRAPHY,
        "DEPTH": DEPTH, "WATER_TYPE": WATER_TYPE,
        "LOCATION": LOCATION,
        "LED_COLOR": LED_COLOR, "VOLTAGE_OUTPUT": VOLTAGE_OUTPUT,

        # options
        "PLUS_X": PLUS_X, "MINUS_X": MINUS_X, "PLUS_Y": PLUS_Y, "MINUS_Y": MINUS_Y,
        "MAGNETIC": MAGNETIC, "NOT_MAGNETIC": NOT_MAGNETIC,
        "HEAVY": HEAVY, "MEDIUM": MEDIUM, "LIGHT": LIGHT,
        "FOAM": FOAM, "PLASTIC": PLASTIC,
        "TOP_A": TOP_A, "TOP_B": TOP_B, "TOP_C": TOP_C,
        "FRESH_UNPOLLUTED": FRESH_UNPOLLUTED, "FRESH_POLLUTED": FRESH_POLLUTED,
        "SALTY_UNPOLLUTED": SALTY_UNPOLLUTED, "SALTY_POLLUTED": SALTY_POLLUTED,
        "BOTH": BOTH, "NEITHER": NEITHER, "ADJACENT": ADJACENT, "DIAGONAL": DIAGONAL,
        "VOLTAGE_1": VOLTAGE_1, "VOLTAGE_2": VOLTAGE_2, "VOLTAGE_3": VOLTAGE_3,
        "VOLTAGE_4": VOLTAGE_4, "VOLTAGE_5": VOLTAGE_5,
        "WHITE": WHITE, "RED": RED, "YELLOW": YELLOW, "GREEN": GREEN, "BLUE": BLUE,
    }

    for k, v in _EXPORTS.items():
        setattr(_main, k, v)
except Exception:
    # If __main__ isn't writable in some environment, ignore.
    pass


